openapi: 3.0.3
info:
  title: Tramways Roadmaps API
  description: Tramways Roadmaps API
  version: 1.0.0
servers:
  - url: http://localhost:8762/tramways/rest/
paths:
  /projects:
    post:
      operationId: 'createProject'
      summary: 'Creates a new project'
      tags: [ 'projects' ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '200':
          description: Ok
    get:
      operationId: 'getProjects'
      summary: 'Gets user projects'
      tags: [ 'projects' ]
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDescription'
    /projects/{id}:
      get:
        summary: 'Gets project'
        operationId: 'getProject'
        tags: [ 'projects' ]
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Ok
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Project'
      put:
        summary: 'Updates a project'
        operationId: 'updateProject'
        tags: [ 'projects' ]
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProjectRequest'
        responses:
          '200':
            description: Ok
      delete:
        summary: 'Deletes a project'
        operationId: 'deleteProject'
        tags: [ 'projects' ]
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
        responses:
          '200':
            $ref: '#/components/responses/Ok'
  /projects/{projectId}/maps:
    post:
      summary: 'Creates a map'
      operationId: 'createMap'
      tags: ['projects']
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMapRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './roadmaps.yaml#/components/schemas/RoadMap'
  /projects/{projectId}/maps/{mapId}:
    get:
      summary: 'Gets a map'
      operationId: 'getMap'
      tags: ['projects']
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './roadmaps.yaml#/components/schemas/RoadMap'
    put:
      summary: 'Updates a map'
      operationId: 'updateMap'
      tags: ['projects']
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMapRequest'
      responses:
        '200':
          description: Ok
    delete:
      summary: 'Deletes a map'
      operationId: 'deleteMap'
      tags: ['projects']
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateProjectRequest:
      type: object
      properties:
        name:
          type: string
    UpdateProjectRequest:
      type: object
      properties:
        name:
          type: string
    CreateMapRequest:
      type: object
      properties:
        map:
          $ref: './roadmaps.yaml#/components/schemas/RoadMap'
    UpdateMapRequest:
      type: object
      properties:
        map:
          $ref: './roadmaps.yaml#/components/schemas/RoadMap'
    ProjectDescription:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        roadMaps:
          type: array
          items:
            $ref: '#/components/schemas/RoadMapDescription'
security:
  - bearerAuth: []
